# Site settings
title: Clinton Andrews Portfolio
email: candrews800@gmail.com
description: Clinton Andrews Portfolio - Web Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.clintonandrews.com" # the base hostname & protocol for your site
github_username:  candrews800

# Build settings
markdown: kramdown
